---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: k8s-practice
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      name: website-pod
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: 0xdod/static-website-k8s:latest
        ports:
        - containerPort: 80
      restartPolicy: Always
---

