---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-agents-controller-port
    port: 50000
    targetPort: 50000
  - name: jenkins-server-port
    port: 8080
    targetPort: 8080
  selector:
    app: jenkins
---
